spring:
  application:
    name: reservation-system
  cache:
    type: simple
  datasource:
    url: jdbc:h2:mem:reservation-systemDB
    username: root
    password: 123
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
      use_minimum_puts: false
      use_second_level_cache: false
      use_query_cache: false
      cache_region_factory: org.hibernate.cache.internal.NoCachingRegionFactory
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379

server:
  shutdown: immediate
  port: 8080
  servlet:
    context-path: /reservation-system